# Generated by Django 4.2.10 on 2024-02-15 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0003_rename_data_added_entry_date_added'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('data', models.ImageField(upload_to='uploaded_images/')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
