# Generated by Django 4.2.10 on 2024-02-15 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0004_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='data',
            field=models.ImageField(upload_to='learning_logs/'),
        ),
    ]
