# Generated by Django 4.2.10 on 2024-02-16 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0007_alter_image_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='data',
            new_name='img_path',
        ),
        migrations.RemoveField(
            model_name='image',
            name='title',
        ),
        migrations.AddField(
            model_name='image',
            name='img_class',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='image',
            name='img_type',
            field=models.CharField(default='sample', max_length=100),
        ),
    ]
