# Generated by Django 4.2.10 on 2024-02-16 12:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0008_rename_data_image_img_path_remove_image_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='img_name',
            field=models.CharField(default=django.utils.timezone.now, editable=False, max_length=255),
            preserve_default=False,
        ),
    ]
