# Generated by Django 4.2.10 on 2024-02-16 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0010_alter_image_id_alter_image_img_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='img_name',
            field=models.CharField(max_length=100),
        ),
    ]
