# Generated by Django 4.2.10 on 2024-02-16 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0012_alter_image_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='img_name',
            field=models.CharField(default='<django.db.models.fields.CharField>_<django.db.models.fields.IntegerField>', max_length=100),
        ),
    ]
