# Generated by Django 4.2.10 on 2024-02-16 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0014_remove_image_img_name_alter_image_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='img_path',
            new_name='img_dir',
        ),
    ]
