# Generated by Django 4.2.10 on 2024-02-16 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0015_rename_img_path_image_img_dir'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='img_class',
            field=models.CharField(default='unclassified', max_length=100),
        ),
    ]
